# Lists of all tickers, tickers with no data within the past 20 business days, and valid tickers

NMS_ticker_symbols = ["AAPL", "AMZN", "GOOG", "AMAT", "AMGN", "AAL", "ADBE", "GOOGL", "ADP", "AKAM", "ATVI", "ADSK",
                      "WBA", "ARNA", "ACAD", "ALXN", "CLMS", "AVGO", "EA", "AMBA", "APOL", "LULU", "AGNC", "JBLU",
                      "ORLY", "ATML", "ACOR", "ADI", "AEGR", "ACIW", "AMTD", "ALTR", "ARCC", "AGIO", "ARLP", "AFSI",
                      "ALNY", "ARMH", "ARIA", "AINV", "ACXM", "ACHN", "ACET", "ABMD", "VA", "LIFE", "ADXS", "SAVE",
                      "AKRX", "ABAX", "ASML", "DWA", "AMCC", "CAR", "ABCO", "JKHY", "AVAV", "AMKR", "ANAC", "AEIS",
                      "MTGE", "CENX", "ASPS", "AMAG", "ALKS", "AFFX", "ACAT", "AAON", "VRSK", "ALSK", "ACTG", "ACAS",
                      "ATHN", "AVHI", "ARWR", "ANGI", "ALGN", "GLPI", "ARRS", "AMCX", "RDEN", "PAAS", "APOG", "ANDE",
                      "AMSC", "AMRS", "AMED", "ALCO", "ADUS", "ACTA", "AAWW", "MDRX", "KLIC", "AZPN", "AHGP", "SHLM",
                      "GIII", "DAVE", "AWAY", "AREX", "ANSS", "AMNB", "AIXG", "ADTN", "ACLS", "HOLI", "BEAV", "ATAX",
                      "DOX", "AVID", "ASNA", "ARAY", "AMBC", "ALGT", "AIRM", "AIMC", "ACHC", "ABY", "TA", "MANH",
                      "LAMR", "ATRO", "ATNI", "APEI", "ANIK", "ANGO", "AMSG", "ALOG", "AEGN", "ZLTQ", "WRLD", "UHAL",
                      "RJET", "CACC", "ATSG", "ASEI", "AROW", "ARCB", "AMRK", "ALRM", "AFAM", "ACSF", "ABGB", "USAP",
                      "STFC", "SEED", "BREW", "AUDC", "ATRI", "APIC", "AOSL", "AMWD", "ACGL", "ABCB", "REXI", "RAIL",
                      "ARTNA", "AGNCP", "ADRO", "KALU", "HOMB", "ATLC", "AMSWA", "AMSF", "ALLT", "AGYS", "CHOP", "CCD",
                      "AYA", "AVNW", "AMRI", "AMCN", "AGII", "AEPI", "ABCW", "SRAQU", "OMAB", "CRMT", "CRESY", "ATRA",
                      "ATEC", "ARLZ", "ARII", "ANAT", "ACRS", "ABDC", "GABC", "EPAX", "CACQ", "ASFI", "ASCMA", "ARCP",
                      "TEAM", "LMIA", "FWP", "CHY", "APLP", "AMRB", "ADAP", "ACTS", "PRTS", "BRKS", "ASYS", "AMPH",
                      "ADVS", "ABUS", "FWRD", "AGFS", "ADNC", "ACBI", "SCAI", "MTGEP", "MPAA", "AXTI", "AVXS", "ASTE",
                      "ASND", "AGIIL", "IPCC", "FNTCU", "CHI", "AGNCB", "ASMI", "ARUN", "ARCPP", "AMSGP", "AIMT",
                      "AAAP", "NBRV", "HDRAU", "AVNU", "AGFSW", "SMACU", "FSAM", "ECACR", "ARWAR", "CACGU", "AMBCW",
                      "BBRY", "BIDU", "BIIB", "BBBY", "MNST", "FITB", "BWLD", "PNRA", "CNBKA", "CBRL", "BMRN", "HBAN",
                      "PDLI", "BRCD", "BGCP", "EGLE", "PACB", "BKCC", "BBEP", "BKMU", "DNKN", "BPOP", "PBYI", "BOBE",
                      "BLUE", "NILE", "ICON", "FIBK", "EWBC", "BCRX", "BCPC", "SBGI", "BRKR", "BOKF", "VIVO", "ONB",
                      "HCBK", "COKE", "BJRI", "BCOR", "UBSH", "TCBI", "SUSQ", "SGMO", "RRGB", "LCUT", "IBTX", "FFBC",
                      "BZUN", "BGFV", "SASR", "NXST", "ZION", "VRA", "SFBS", "SBNY", "JBSS", "JACK", "BV", "BBOX",
                      "TECH", "NRIM", "NPBC", "IBKR", "BAMM", "NBIX", "FMBI", "FIVE", "CNOB", "CALA", "SBLK", "SBCF",
                      "ROLL", "HTBI", "GBDC", "FIZZ", "FFKT", "FCNCA", "BMTC", "BLKB", "BBSI", "BABY", "OZRK", "COB",
                      "CBSH", "BUSE", "BRKL", "BONT", "BOJA", "BEAT", "XBKS", "WASH", "WABC", "UCBI", "PPBI", "NBTB",
                      "MBVT", "INBK", "CSFL", "CSBK", "CATY", "BOFI", "BLMN", "BBRG", "WIFI", "WIBC", "LOB", "IBCP",
                      "FNBC", "FARM", "EBSB", "CCBG", "CBNJ", "CBF", "BIND", "BELFB", "UBNK", "TRST", "TOWN", "TBNK",
                      "SGBK", "NWBI", "NFBK", "MNRO", "LBAI", "GBT", "FBNK", "CBPO", "BSRR", "BSFT", "BPFH", "BONA",
                      "BLDR", "BIOS", "BDGE", "BDE", "BCOM", "BANF", "TRIB", "SVA", "PFBC", "IBOC", "GSBC", "STBA",
                      "SBSI", "PLAY", "OSBC", "LBRDA", "KYTH", "ISBC", "FNLC", "BSET", "BOOM", "BHBK", "BCOV", "BANR",
                      "TCBK", "SHBI", "NBBC", "MBWM", "INDB", "GBCI", "FXCB", "FBIZ", "EPAY", "TCBIP", "TBBK", "STCK",
                      "RCKY", "OKSB", "MCBC", "GBNK", "DCOM", "BUFF", "BOTA", "BBEPP", "BANX", "UBSI", "TBK", "SNBC",
                      "RBCAA", "MRLN", "HMPR", "HAWK", "FFIN", "COLB", "BRLI", "BKYF", "BBNK", "BBCN", "PWOD", "PMBC",
                      "PACW", "EVBS", "ESSA", "BPMC", "UBFO", "RVSB", "PEBO", "HWBK", "HBCP", "GNBC", "FCBC", "EBTC",
                      "BRDR", "BPOPN", "BFIN", "BECN", "WTBA", "TCBIL", "SYBT", "METR", "FSBK", "CBSHP", "BPFHW",
                      "BNCL", "BGNE", "BELFA", "SUBK", "SIBC", "LBRDK", "HBNC", "FITBI", "FBNC", "BDBD", "TCBIW",
                      "SBLKL", "GEVA", "BPOPM", "SBNYW", "OPB", "FFBCW", "CATYW", "ZIONZ", "ZIONW", "SBBP", "OSBCP",
                      "ISM", "EQBK", "CTBI", "BPFHP", "BOFIL", "BANFP", "BITI", "HBANP", "HBANO", "MSFT", "INTC",
                      "CSCO", "CMCSA", "SBUX", "COST", "CATM", "NVDA", "FTR", "CELG", "SNDK", "SCTY", "ETFC", "SYMC",
                      "DISH", "CERN", "STX", "ESRX", "CSX", "CTSH", "LRCX", "CA", "SHLD", "FAST", "WDC", "GT", "KLAC",
                      "CALM", "CTXS", "LLTC", "CME", "CHKP", "CSIQ", "GERN", "CSII", "SINA", "FOXA", "KHC", "WB",
                      "NWSA", "CHRW", "HAIN", "CTRP", "CLDX", "CINF", "CROX", "CHTR", "SWHC", "PSUN", "CREE", "TECD",
                      "SLM", "TSCO", "SPTN", "QLGC", "SPWR", "CLMT", "SANM", "CZR", "CY", "CONN", "WEN", "PSEC", "INCY",
                      "CTAS", "WBMD", "UPL", "SONC", "ROVI", "GNTX", "CRUS", "PPC", "CYOU", "CSGS", "COLM", "CEMP",
                      "XONE", "MFRM", "CYBR", "ULTA", "CPLA", "PDCO", "LNCO", "JAZZ", "CLVS", "CCIH", "CBOE", "OLED",
                      "MENT", "DEST", "CASY", "NUAN", "MTSC", "MSCC", "MPEL", "FSC", "ERIE", "CLNE", "UTHR", "ISIL",
                      "INFN", "CPLP", "ZBRA", "UTSI", "SIMO", "SBAC", "NEOG", "NAVI", "LKQ", "LANC", "FDML", "CDW",
                      "SCVL", "RPTP", "PCH", "NTRS", "MASI", "LMCA", "JASO", "ISLE", "CSGP", "CG", "CAKE", "SNC",
                      "SCHL", "PRTA", "PRGS", "ORIT", "NWS", "MIK", "LSCC", "IRBT", "FOX", "DISCA", "CAMP", "XCRA",
                      "SBRA", "PRXL", "PRSC", "OTEX", "NCLH", "HFWA", "HBHC", "FLDM", "EMMS", "CRAY", "COHU", "UMPQ",
                      "RPXC", "NDSN", "GEOS", "ELNK", "ECPG", "DGAS", "CYNO", "CAFD", "CAC", "VICR", "SIAL", "SATS",
                      "RSYS", "RECN", "POOL", "MEOH", "LOPE", "LINC", "IBKC", "GPOR", "FSTR", "DMRC", "CSCD", "CMCSK",
                      "CDK", "CASH", "VOXX", "TAXI", "PNNT", "ON", "MDCO", "MANT", "LMNX", "IXYS", "HRZN", "HMSY",
                      "FNSR", "DISCK", "CTRN", "CSAL", "CRZO", "CRTO", "CPHD", "COWN", "COMM", "CCNE", "CAVM", "TRMK",
                      "TESO", "SMCI", "ROIC", "PRIM", "PODD", "NATI", "LMCK", "ISCA", "INAP", "HWCC", "FTD", "FMER",
                      "FBRC", "CYTK", "CWCO", "CVGW", "CTRE", "CSOD", "CORE", "CMCO", "CFMS", "CDNS", "SPNC", "SGI",
                      "PLCE", "PCTY", "PCCC", "NDLS", "KEYW", "IPGP", "HOFT", "HAFC", "GNCMA", "EFSC", "CVLT", "CVBF",
                      "CNSL", "CHKE", "CETV", "CECO", "CCRN", "CASS", "VWR", "UCTT", "TRS", "THOR", "THFF", "TFSL",
                      "STRL", "SNHY", "PRSS", "NWPX", "MATW", "LDRH", "IRDM", "IMMR", "GLRE", "FELE", "FDUS", "ELRC",
                      "CPRT", "CMTL", "CCXI", "CCOI", "WDFC", "TW", "TICC", "SP", "SHEN", "SGMS", "RNST", "OTTR",
                      "MTRX", "IMOS", "ICLR", "HMHC", "GOOD", "FULT", "FRME", "FEIC", "CVGI", "CSTE", "CNMD", "CISG",
                      "CHEF", "CHDN", "CHCO", "CGNX", "VSEC", "UMBF", "SPIL", "SCSS", "QUMU", "QDEL", "PWRD", "NTLS",
                      "NCMI", "HTHT", "DCIX", "CWST", "CVTI", "CTWS", "CTCM", "CRAI", "CHMA", "CGO", "TCRD", "TCPC",
                      "SRCE", "SABR", "PMTS", "PLXS", "PLPC", "PGC", "OPHT", "OCFC", "NMRX", "MBTF", "LNDC", "LKFN",
                      "KOPN", "IART", "FRAN", "DTLK", "CRNT", "COHR", "CNTF", "CMPR", "CFFN", "ZIXI", "YORW", "VRTU",
                      "SMTC", "SLRC", "RGEN", "MIDD", "HURC", "GAIN", "CYBX", "CTRL", "CRWN", "CPSI", "CKEC", "CHMG",
                      "CHFC", "WSTC", "WSFS", "WIRE", "UCFC", "SPSC", "PBPB", "NRCIB", "MSEX", "MCRI", "LORL", "LION",
                      "LAYN", "KZ", "HQCL", "GLAD", "FSRV", "ELON", "CXRX", "CUTR", "CONE", "COBZ", "CHUY", "CECE",
                      "CDXS", "TUES", "SFNC", "SEIC", "RENT", "PSTB", "PFMT", "HTBK", "FSFR", "FOGO", "FDEF", "CTG",
                      "CRVL", "CPTA", "COLL", "CHSCP", "CEVA", "CENT", "CCMP", "UVSP", "TAST", "SUNS", "SSB", "PSEM",
                      "PKOH", "PFIS", "PCBK", "NATL", "LMOS", "KRNY", "ITRN", "INFA", "IGTE", "GLDD", "GARS", "FFIC",
                      "DWSN", "CVCO", "CSWC", "CPIX", "CFNL", "CFFI", "STLY", "SBRAP", "PULB", "PFLT", "OXLC", "OFS",
                      "NRCIA", "NEWP", "MCGC", "JRJC", "JJSF", "HCCI", "GAINO", "FUNC", "FSV", "FOXF", "CTHR", "CSUN",
                      "CSQ", "CRRC", "CPHR", "COVS", "CMFN", "CKSW", "CENTA", "WTFC", "WLTW", "TGA", "SENEB", "SENEA",
                      "NCOM", "MRD", "MRCC", "LOJN", "LMNR", "LABL", "ITIC", "IRCP", "GTLS", "DLTR", "XRAY", "ODP",
                      "DXCM", "DATE", "DMND", "ODFL", "IDTI", "DAKT", "KTOS", "FANG", "DMLP", "DEPO", "DTSI", "STLD",
                      "DGII", "DGICA", "SIRO", "SIGM", "DORM", "DXPE", "KRNT", "DIOD", "DFRG", "DRNA", "DERM", "TWIN",
                      "TRAK", "DXM", "DSPG", "DSGX", "DXLG", "DLTH", "QQQX", "DSKY", "DMTX", "DHIL", "VDTH", "UDF",
                      "MDM", "DISCB", "DBVT", "DHXM", "DGICB", "CHW", "YERR", "EBAY", "LINE", "EXPE", "EXPD", "EXEL",
                      "ENDP", "EQIX", "EGHT", "EXXI", "MCEP", "UEIC", "MGEE", "IEP", "ERIC", "ECHO", "EVEP", "PNK",
                      "STRA", "ERII", "ECYT", "ENSG", "ELGX", "ENOC", "EBIX", "LOCO", "EXTR", "EXPO", "ESGR", "EFII",
                      "REGI", "EIGI", "ECOL", "PTEN", "PETS", "EVLV", "ENTA", "PEGI", "LECO", "FNGN", "EZPW", "EXLS",
                      "ESLT", "EPIQ", "EGOV", "PERY", "PDCE", "EXFO", "WERN", "EXAC", "EROC", "EMITF", "EEFT", "SPKE",
                      "PLUS", "NSIT", "MFLX", "EHTH", "VNOM", "ELOS", "MGIC", "LONG", "ETSY", "ENTG", "EMCI", "SYKE",
                      "RELL", "HEES", "FXEN", "EXLP", "ESND", "EPZM", "ENVI", "RUSHA", "EZCH", "ESIO", "EDIT", "SFXE",
                      "HTLD", "EDGE", "SPI", "EMMSP", "RUSHB", "KE", "ENZY", "FXENP", "EBAYL", "FB", "FSLR", "WFM",
                      "FFIV", "FISV", "FLEX", "FEYE", "FTNT", "FLIR", "FLWS", "PBCT", "FOSL", "UFCS", "SIVB", "SFM",
                      "UFPI", "UNFI", "FCS", "FARO", "TFM", "SVVC", "FNFG", "LPLA", "FUEL", "KCAP", "GIFI", "FRGI",
                      "FMI", "FISI", "MBFI", "FORM", "FINL", "FFNW", "WSBF", "SAFM", "MSFG", "GSM", "FSYS", "FRED",
                      "FORR", "WFD", "VIRT", "NEWS", "NATH", "INTL", "FPRX", "NICK", "MOFG", "FRSH", "WAFD", "SNAK",
                      "PROV", "LTXB", "HTLF", "FTEK", "FORTY", "FRPH", "FGEN", "PNFP", "FLXS", "SIVBO", "HBOS", "FUND",
                      "FISH", "WHF", "MNRK", "FSCFL", "SQBK", "INTLL", "WTFCM", "WHFBL", "WAFDW", "FTRPR", "WSFSL",
                      "WTFCW", "GILD", "MRVL", "VOD", "PCLN", "GMCR", "GRPN", "GPRO", "GRMN", "TROW", "Z", "KNDI",
                      "RGLD", "GPRE", "GLBL", "MLNK", "GOV", "GOLD", "JCOM", "HCSG", "GLUU", "MYGN", "LBTYA", "ULTI",
                      "GOGO", "HSON", "SGEN", "ININ", "GLNG", "GILT", "THRM", "GSOL", "GAME", "WMGI", "PENN", "SIGI",
                      "RUTH", "QVCA", "LBTYK", "IILG", "VNET", "NAVG", "PRAA", "KTWO", "IRG", "HMIN", "GMLP", "GMAN",
                      "GHDX", "ROCK", "PRGX", "MOLG", "LILA", "HUBG", "GSIT", "GSIG", "NWLI", "KANG", "HCKT", "GRFS",
                      "WEB", "NAME", "MYRG", "MTCH", "LHCG", "GK", "GBLI", "WEYS", "GOGL", "IGLD", "GURE", "GASS",
                      "CIGI", "TRNX", "SAFT", "LILAK", "GOODN", "GLPG", "HURN", "ZG", "WWWW", "SUTR", "LBTYB", "JRVR",
                      "GAINN", "QVCB", "GRSHU", "GAINP", "GLADO", "GOODP", "GBLIZ", "OPK", "SIRI", "HAS", "PYPL",
                      "MHLD", "HSIC", "HA", "HZNP", "WIN", "HIMX", "SNH", "HOLX", "HPT", "NIHD", "HWKN", "HDS", "SSNC",
                      "RYAAY", "HSNI", "HSII", "MLHR", "PICO", "HTCH", "HSTM", "HIBB", "TYPE", "MKTX", "JBHT", "SLGN",
                      "INOV", "HLIT", "TTS", "MTSI", "LGIH", "IPCM", "HWAY", "HMST", "IPHS", "HTWR", "HELE", "HDP",
                      "MGLN", "HALO", "TTEC", "SPOK", "LPNT", "INCR", "HCOM", "HAYN", "SPWH", "LITE", "HQY", "TSC",
                      "PRAH", "LTRPA", "ZINC", "WLRHU", "SHLDW", "HCM", "HKTV", "HDNG", "HBHCL", "LTRPB", "SPNE",
                      "PATI", "MHLDO", "TSLA", "YHOO", "NFLX", "QCOM", "MU", "REGN", "TXN", "MAT", "SPLS", "INO", "MAR",
                      "VRTX", "ZNGA", "RLYP", "ROST", "MDLZ", "TMUS", "SWKS", "ISRG", "SRCL", "PAYX", "MCHP", "XLNX",
                      "MXIM", "URBN", "NTAP", "INTU", "ILMN", "PCAR", "SRPT", "MDVN", "ICPT", "SOHU", "NTES", "TERP",
                      "TASR", "YY", "VRSN", "VVUS", "SWIR", "JD", "NDAQ", "NVAX", "VIAB", "MDSO", "TRIP", "WPRT", "VIA",
                      "RMBS", "RCII", "PMCS", "NYMT", "JUNO", "PTCT", "SYNA", "IDXX", "PTLA", "PCRX", "ONTY", "TIVO",
                      "SNPS", "SPPI", "QSII", "UNTD", "PZZA", "STMP", "RARE", "SNI", "IDCC", "SPLK", "SIR", "QRVO",
                      "OCLR", "ZUMZ", "YRCW", "WWD", "VRNT", "SAAS", "ORIG", "MMSI", "INFI", "IMGN", "ZU", "TTWO",
                      "TTEK", "SZYM", "QLIK", "PLCM", "OUTR", "MELI", "LSTR", "UBNT", "TUBE", "SKYW", "SKUL", "SIEN",
                      "RAVN", "ONCE", "NTGR", "LLNW", "WRES", "SQNM", "SONS", "SNCR", "SGYP", "SFLY", "MGPI", "MCRB",
                      "JAKK", "ITRI", "IIIN", "ZEUS", "TXRH", "TTPH", "KITE", "XNPT", "TILE", "SODA", "SHLO", "REIS",
                      "PLAB", "OREX", "ORBC", "NTCT", "MSTR", "MPWR", "JOBS", "IQNT", "IPXL", "ZFGN", "WSBC", "TSYS",
                      "TSRA", "TREE", "TNGO", "SPAR", "RTIX", "PTC", "PRFT", "OMCL", "OIIM", "NXTM", "NUVA", "NTK",
                      "LYTS", "LXRX", "LPSN", "IRWD", "WOOF", "TZOO", "SEAC", "SCLN", "SCHN", "RP", "PGNX", "OSIS",
                      "MTEX", "JOUT", "XBIT", "WING", "SZMK", "SEDG", "QNST", "PSMT", "MIND", "MGI", "LOGM", "LNCE",
                      "KELYA", "INSM", "ZAGG", "XXIA", "VTAE", "VSAR", "VRTS", "TAX", "SAIA", "RSTI", "QLYS", "PTIE",
                      "PLKI", "OVTI", "MXWL", "MRCY", "MORN", "MNTA", "MIFI", "MERC", "KVHI", "IONS", "IMPV", "IMKTA",
                      "ICFI", "VSAT", "UPIP", "TNAV", "SYNT", "STRS", "SREV", "SRDX", "POZN", "NK", "MTSN", "MLAB",
                      "MKTO", "MINI", "IIVI", "UEPS", "TRUE", "TRGT", "THRX", "TEDU", "STKL", "SHOR", "RIGL", "QLTI",
                      "POWL", "PDFS", "NTRI", "NANO", "KPTI", "ITCI", "ICUI", "VIAV", "VASC", "JIVE", "JST", "IIJI",
                      "JSM", "JNP", "KMDA", "KIRK", "KFX", "KBAL", "KFRC", "KURA", "KLXI", "KELYB", "WYNN", "VNR",
                      "VIP", "SSYS", "MLNX", "MEMP", "LGCY", "RDWR", "WIX", "NCTY", "TSEM", "SHOO", "MMLP", "PERI",
                      "NICE", "TRMB", "SILC", "NVCR", "MRTN", "ORBK", "MCOX", "LVNTA", "LOGI", "LIOX", "LAWS", "SLAB",
                      "LFUS", "VNRBP", "VNRAP", "MMYT", "XNET", "LMNS", "SEMI", "MOBI", "LQDT", "PTXP", "PTNR", "OXLCO",
                      "CCLP", "USLM", "STNR", "RRM", "MRKT", "LVNTB", "VNRCP", "NVMI", "MIME", "MESO", "LIVN", "LGCYO",
                      "OXLCP", "OXLCN", "LGCYP", "MYL", "TITN", "UTMD", "WMAR", "VISN", "MOMO", "MGRC", "MGNX", "MDCA",
                      "MARPS", "MYOK", "MTLS", "MKSI", "SMRT", "MOBL", "MDAS", "MCRL", "MCHX", "MITL", "VLGEA", "NYMTO",
                      "SKLNU", "INFO", "NYMTP", "NXPI", "QGEN", "NKTR", "YNDX", "QURE", "OFIX", "NSSC", "NNBR", "NTRA",
                      "PKT", "NCIT", "CNV", "NUTR", "NTRSP", "OSUR", "OMED", "OTIC", "OCLSW", "OHAI", "ONNN", "WPPGY",
                      "SHPG", "QIWI", "PCYC", "SGNT", "POWI", "PEGA", "ISIS", "IPAR", "PATK", "PHII", "SNDX", "PHIIK",
                      "PVTB", "PINC", "PCTI", "SGRY", "CSRE", "TECU", "PMFG", "PVTBP", "CLTX", "QADA", "QADB", "SALE",
                      "SSRI", "RUN", "RNWK", "RLOC", "RNET", "RCPT", "RELY", "RGNX", "REMY", "STRZA", "SCSC", "USTR",
                      "SYUT", "SQI", "STB", "ISSC", "ISSI", "VRNS", "UACL", "SLMAP", "SLMBP", "STRZB", "SRCLP", "SRSC",
                      "TWOU", "TLGT", "TSRO", "VYGR", "VTL", "USAK", "TRVN", "TRIV", "TTMI", "TESS", "CTMX", "UTEK",
                      "UTIW", "UBIC", "INVA", "TMUSP", "VECO", "VIAVV", "WETF", "WILN", "WINVV", "XOOM", "YDLE",
                      "ZCVVV", "ZAVVV", "APSA", "ASPX", "FNBG", "BSDM", "CTRX", "CBRX", "CERCZ", "CFRXW", "CHSCM",
                      "CHSCN", "CHSCL", "CHSCO", "CHYR", "CMSB", "CTCT", "IBKCP", "CSWI", "CSALV", "CSWIV", "DRIV",
                      "EDS", "EOPN", "ESBF", "EVRY", "FCZA", "FCZAP", "MBFIP", "MFIN", "GOODO", "COWNL", "HBNK", "HLSS",
                      "HPTX", "HTWO", "IAC", "IARTV", "IBCA", "ICEL", "IMI", "IMRS", "IOSP", "IPAS", "IRDMB", "IVAC",
                      "IVAN", "KURO", "LEVYU", "LEVY", "LPHI", "MWIV", "NBTF", "NOVB", "NPSP", "PEOP", "PETM", "PENX",
                      "PRLS", "PTRY", "RGDO", "RNA", "RRST", "RVBD", "SGRH", "SIMG", "SLXP", "TGE", "UPI", "VIEW",
                      "VLCCF", "VOLC", "VSCI", "VTSS", "WLBPZ", "CHEKU", "CNDO", "COBK", "INGN", "INWK", "LILKV",
                      "LILAV", "LITEV", "SPNEV"]

missing_recent_data = ['PTIE', 'TRAK', 'CY', 'ORIT', 'BEAT', 'NPBC', 'EZCH', 'LGCYP', 'LLTC', 'LGCYO', 'LONG', 'NTRSP',
                       'LMCK', 'NRCIB', 'ESRX', 'ARMH', 'CBRX', 'COBZ', 'HWAY', 'AGII', 'PCCC', 'ARUN', 'CMCSK', 'ASPX',
                       'NEWP', 'WWWW', 'REIS', 'PVTBP', 'QVCA', 'SMACU', 'ROVI', 'CMSB', 'XNPT', 'MDVN', 'WFD', 'FTR',
                       'MBFIP', 'SUBK', 'NILE', 'SGI', 'SQBK', 'ASEI', 'KURO', 'EPAX', 'BEAV', 'PLCM', 'ARWAR', 'ORBK',
                       'CELG', 'SIRO', 'SYUT', 'ARCP', 'VLCCF', 'CACGU', 'SYNT', 'KEYW', 'MLNX', 'NTK', 'FBNK', 'KTWO',
                       'SRCLP', 'MOBI', 'SHLDW', 'ISSI', 'VIAVV', 'MTGE', 'LMCA', 'FSYS', 'VNR', 'GLBL', 'CSAL', 'FCZAP',
                       'CAFD', 'TTPH', 'LOGM', 'ACAT', 'NXTM', 'NIHD', 'BITI', 'PHII', 'AMCC', 'SONS', 'AREX', 'ACSF',
                       'CECO', 'LVNTB', 'PWRD', 'RSYS', 'AGNCB', 'SBRAP', 'WILN', 'IMI', 'MBFI', 'JST', 'RVBD', 'ASNA',
                       'LILAV', 'QSII', 'MOLG', 'ECYT', 'QVCB', 'WHFBL', 'DERM', 'HPT', 'MDM', 'TAX', 'PVTB', 'ZFGN',
                       'ABY', 'COB', 'IPHS', 'DTSI', 'ADVS', 'ZCVVV', 'EOPN', 'XCRA', 'ONTY', 'FEIC', 'BIOS', 'VVUS',
                       'IMPV', 'THRX', 'GNBC', 'PCYC', 'CFNL', 'HMPR', 'VRTU', 'ABGB', 'XXIA', 'GAME', 'OXLCN', 'FISH',
                       'CNDO', 'ECACR', 'WINVV', 'JIVE', 'VTSS', 'HCOM', 'INFA', 'JUNO', 'PULB', 'AFAM', 'ACAS', 'OCLR',
                       'AVHI', 'MNRK', 'PHIIK', 'CA', 'LIOX', 'ININ', 'MSFG', 'ABCW', 'PCLN', 'FINL', 'EXXI', 'LPHI',
                       'LMOS', 'AMBCW', 'AVXS', 'STRZB', 'CERCZ', 'WTFCW', 'TRIV', 'IXYS', 'ZLTQ', 'BONA', 'ZU',
                       'IRDMB', 'CLTX', 'HDNG', 'FTRPR', 'RENT', 'PDLI', 'FNBC', 'ETFC', 'UBNK', 'DCIX', 'HSNI', 'FMER',
                       'SHOR', 'FNFG', 'ZAGG', 'FSFR', 'SQI', 'SIR', 'MBTF', 'WIN', 'AHGP', 'PKT', 'PGNX', 'BDBD',
                       'PSUN', 'ENOC', 'ISIS', 'QLIK', 'FRSH', 'GBNK', 'CACQ', 'FDEF', 'MCEP', 'AMSG', 'YHOO', 'BOFIL',
                       'SZYM', 'LINE', 'BNCL', 'MWIV', 'RSTI', 'NAVG', 'YDLE', 'LION', 'RPXC', 'PNK', 'EDS', 'ARLZ',
                       'PNRA', 'IIJI', 'TCRD', 'LITEV', 'FUEL', 'BBCN', 'SQNM', 'SLXP', 'APLP', 'USTR', 'EPIQ', 'RRST',
                       'AFSI', 'WMGI', 'LAYN', 'REXI', 'RTIX', 'STCK', 'ARRS', 'ACTS', 'PEGI', 'TAXI', 'SKUL', 'CAVM',
                       'ZIONW', 'MRKT', 'IRG', 'GBLIZ', 'KITE', 'NEWS', 'ARCPP', 'EVEP', 'VSCI', 'IBKC', 'HKTV', 'ARII',
                       'MITL', 'LDRH', 'VIAB', 'HTCH', 'AGFSW', 'PETM', 'OUTR', 'NUTR', 'RELY', 'INTLL', 'FCS', 'HBHCL',
                       'CYOU', 'MENT', 'SIVBO', 'HTWR', 'SGYP', 'CBF', 'HLSS', 'CXRX', 'ESIO', 'UPL', 'RDEN', 'MTSN',
                       'HQCL', 'FNBG', 'UBSH', 'EVBS', 'DEPO', 'OKSB', 'LMIA', 'WPPGY', 'GPOR', 'TUBE', 'PTXP', 'WMAR',
                       'MFLX', 'WLBPZ', 'GEVA', 'FMI', 'GARS', 'IPCM', 'SHLO', 'LOJN', 'CPLA', 'GAINP', 'UPIP', 'FRAN',
                       'RPTP', 'CHYR', 'DGAS', 'WSTC', 'UPI', 'KFX', 'VDTH', 'FXENP', 'SGBK', 'STRZA', 'KANG', 'YERR',
                       'FXEN', 'VA', 'ZINC', 'SONC', 'GSOL', 'HMIN', 'MSCC', 'CSFL', 'VASC', 'IGTE', 'SPIL', 'BONT',
                       'CSBK', 'SYMC', 'CSWIV', 'AMTD', 'LABL', 'SBLKL', 'BSFT', 'ANAC', 'TRGT', 'CRRC', 'INTL', 'SIAL',
                       'SFLY', 'IILG', 'ESBF', 'NATL', 'POZN', 'TTS', 'VIA', 'FNTCU', 'MOBL', 'TICC', 'PTRY', 'MHLDO',
                       'SPLS', 'LGCY', 'CTRX', 'CFRXW', 'VSAR', 'MLNK', 'EVLV', 'RECN', 'ELGX', 'DFRG', 'CTCT', 'SIGM',
                       'LMNS', 'SCSS', 'NANO', 'FSC', 'PRGX', 'BOBE', 'BDGE', 'SNBC', 'MCOX', 'CHOP', 'CHFC', 'FRED',
                       'SUSQ', 'GNCMA', 'JASO', 'ISCA', 'ASCMA', 'CCIH', 'MYOK', 'AMCN', 'LPNT', 'ELRC', 'DNKN', 'AIRM',
                       'CTRP', 'BCOM', 'MINI', 'CRZO', 'VNRBP', 'BBNK', 'IPXL', 'ADRO', 'STNR', 'TNGO', 'CMFN', 'CTRL',
                       'NBBC', 'EMMSP', 'DSKY', 'DTLK', 'CNTF', 'FBRC', 'GK', 'BBEP', 'CATYW', 'OREX', 'FDML', 'PSTB',
                       'BBOX', 'WRES', 'EROC', 'PRLS', 'ASFI', 'MPEL', 'THOR', 'CEMP', 'UTEK', 'OVTI', 'TMUSP', 'BDE',
                       'UBNT', 'ESND', 'MIFI', 'TIVO', 'VTL', 'GMAN', 'GLADO', 'CTCM', 'CSALV', 'AYA', 'SRAQU', 'SSRI',
                       'QLGC', 'DHXM', 'WLRHU', 'BBEPP', 'AGIIL', 'BRDR', 'TCBIW', 'CLMS', 'PMCS', 'OZRK', 'ELNK',
                       'ASMI', 'ELON', 'CBSHP', 'VOLC', 'ARIA', 'MDCO', 'SMRT', 'BHBK', 'ABDC', 'UDF', 'PTLA', 'GRSHU',
                       'MDAS', 'PRXL', 'MFRM', 'BAMM', 'FFBCW', 'BPFHW', 'TUES', 'FOGO', 'METR', 'IQNT', 'BSDM', 'FFKT',
                       'AMAG', 'PCBK', 'FCZA', 'OPHT', 'CYBX', 'AAAP', 'SCAI', 'GHDX', 'APSA', 'TSYS', 'SNH', 'PEOP',
                       'AVNU', 'RLOC', 'HTWO', 'UNTD', 'OCLSW', 'BRCD', 'MXWL', 'VTAE', 'PSEM', 'ABAX', 'MEMP', 'CHEKU',
                       'SUTR', 'HPTX', 'HCBK', 'CISG', 'PENX', 'AMRI', 'NK', 'WSFSL', 'NTLS', 'ATHN', 'RJET', 'FXCB',
                       'NCOM', 'MYL', 'NPSP', 'TNAV', 'EFII', 'SHLM', 'UBIC', 'AFFX', 'SIMG', 'DEST', 'ACXM', 'TECU',
                       'SGNT', 'LEVY', 'ISIL', 'ZAVVV', 'WAFDW', 'GOV', 'DMTX', 'MDSO', 'IDTI', 'INAP', 'IARTV', 'CSCD',
                       'IPAS', 'CKEC', 'PMFG', 'CETV', 'NCIT', 'FSBK', 'EDGE', 'IPCC', 'CKSW', 'AEGR', 'LTXB', 'SWHC',
                       'MNTA', 'TSRA', 'TFM', 'CRAY', 'AEPI', 'NOVB', 'INWK', 'DMND', 'OHAI', 'LVNTA', 'SPNEV', 'FTD',
                       'JNP', 'WBMD', 'OMED', 'CBNJ', 'KZ', 'WIBC', 'TASR', 'SCLN', 'HDP', 'ENZY', 'NTRI', 'VNRAP',
                       'TSRO', 'LILKV', 'LEVYU', 'MCGC', 'QLTI', 'TECD', 'DAVE', 'HBHC', 'RRM', 'SPNC', 'SBNYW', 'COBK',
                       'SLMAP', 'BREW', 'ZIONZ', 'MCRL', 'COVS', 'CSRE', 'BOJA', 'STB', 'UTIW', 'ORIG', 'TGE', 'ACTA',
                       'MKTO', 'BWLD', 'ATML', 'SODA', 'VNRCP', 'AIMT', 'CVTI', 'WEB', 'ONNN', 'AKRX', 'ALOG', 'FNGN',
                       'SNC', 'VWR', 'SNAK', 'ACHN', 'BOTA', 'XBKS', 'EXLP', 'BPFHP', 'OPB', 'KCAP', 'SGRH', 'SEMI',
                       'TESO', 'FNSR', 'BABY', 'SNHY', 'BKYF', 'EXAC', 'SKLNU', 'INCR', 'GAINO', 'ONCE', 'PLKI',
                       'MTGEP', 'CNV', 'MRD', 'SALE', 'CPHD', 'LNCO', 'RGDO', 'AIXG', 'RLYP', 'CPHR', 'DATE', 'NBTF',
                       'ULTI', 'UACL', 'RCPT', 'ADNC', 'APOL', 'GOODO', 'HBOS', 'EVRY', 'NMRX', 'BKMU', 'BBRY', 'MBVT',
                       'TERP', 'REMY', 'SFXE', 'KLXI', 'IMRS', 'XOOM', 'HAWK', 'PERY', 'UCFC', 'GOODP', 'FSCFL', 'HBNK',
                       'DWA', 'HDS', 'GMCR', 'EIGI', 'SZMK', 'SPAR', 'LNCE', 'SAAS', 'BBRG', 'DXM', 'PRSC', 'SHPG',
                       'IBCA', 'OSBCP', 'ELOS', 'BOFI', 'ISM', 'WFM', 'PRSS', 'AMSGP', 'SNDK', 'NRCIA', 'EMCI', 'CHKE',
                       'HDRAU', 'ICEL', 'CTWS', 'SRSC', 'IBKCP', 'CSUN', 'CYNO', 'TYPE', 'SNI']

valid_ticker_symbols = ['AAPL', 'AMZN', 'GOOG', 'AMAT', 'AMGN', 'AAL', 'ADBE', 'GOOGL', 'ADP', 'AKAM', 'ATVI', 'ADSK',
                        'WBA', 'ARNA', 'ACAD', 'ALXN', 'AVGO', 'EA', 'AMBA', 'LULU', 'AGNC', 'JBLU', 'ORLY', 'ACOR',
                        'ADI', 'ACIW', 'ALTR', 'ARCC', 'AGIO', 'ARLP', 'ALNY', 'AINV', 'ACET', 'ABMD', 'LIFE', 'ADXS',
                        'SAVE', 'ASML', 'CAR', 'ABCO', 'JKHY', 'AVAV', 'AMKR', 'AEIS', 'CENX', 'ASPS', 'ALKS', 'AAON',
                        'VRSK', 'ALSK', 'ACTG', 'ARWR', 'ANGI', 'ALGN', 'GLPI', 'AMCX', 'PAAS', 'APOG', 'ANDE', 'AMSC',
                        'AMRS', 'AMED', 'ALCO', 'ADUS', 'AAWW', 'MDRX', 'KLIC', 'AZPN', 'GIII', 'AWAY', 'ANSS', 'AMNB',
                        'ADTN', 'ACLS', 'HOLI', 'ATAX', 'DOX', 'AVID', 'ARAY', 'AMBC', 'ALGT', 'AIMC', 'ACHC', 'TA',
                        'MANH', 'LAMR', 'ATRO', 'ATNI', 'APEI', 'ANIK', 'ANGO', 'AEGN', 'WRLD', 'UHAL', 'CACC', 'ATSG',
                        'AROW', 'ARCB', 'AMRK', 'ALRM', 'USAP', 'STFC', 'SEED', 'AUDC', 'ATRI', 'APIC', 'AOSL', 'AMWD',
                        'ACGL', 'ABCB', 'RAIL', 'ARTNA', 'AGNCP', 'KALU', 'HOMB', 'ATLC', 'AMSWA', 'AMSF', 'ALLT',
                        'AGYS', 'CCD', 'AVNW', 'OMAB', 'CRMT', 'CRESY', 'ATRA', 'ATEC', 'ANAT', 'ACRS', 'GABC', 'TEAM',
                        'FWP', 'CHY', 'AMRB', 'ADAP', 'PRTS', 'BRKS', 'ASYS', 'AMPH', 'ABUS', 'FWRD', 'AGFS', 'ACBI',
                        'MPAA', 'AXTI', 'ASTE', 'ASND', 'CHI', 'NBRV', 'FSAM', 'BIDU', 'BIIB', 'BBBY', 'MNST', 'FITB',
                        'CNBKA', 'CBRL', 'BMRN', 'HBAN', 'BGCP', 'EGLE', 'PACB', 'BKCC', 'BPOP', 'PBYI', 'BLUE', 'ICON',
                        'FIBK', 'EWBC', 'BCRX', 'BCPC', 'SBGI', 'BRKR', 'BOKF', 'VIVO', 'ONB', 'COKE', 'BJRI', 'BCOR',
                        'TCBI', 'SGMO', 'RRGB', 'LCUT', 'IBTX', 'FFBC', 'BZUN', 'BGFV', 'SASR', 'NXST', 'ZION', 'VRA',
                        'SFBS', 'SBNY', 'JBSS', 'JACK', 'BV', 'TECH', 'NRIM', 'IBKR', 'NBIX', 'FMBI', 'FIVE', 'CNOB',
                        'CALA', 'SBLK', 'SBCF', 'ROLL', 'HTBI', 'GBDC', 'FIZZ', 'FCNCA', 'BMTC', 'BLKB', 'BBSI', 'CBSH',
                        'BUSE', 'BRKL', 'WASH', 'WABC', 'UCBI', 'PPBI', 'NBTB', 'INBK', 'CATY', 'BLMN', 'WIFI', 'LOB',
                        'IBCP', 'FARM', 'EBSB', 'CCBG', 'BIND', 'BELFB', 'TRST', 'TOWN', 'TBNK', 'NWBI', 'NFBK', 'MNRO',
                        'LBAI', 'GBT', 'CBPO', 'BSRR', 'BPFH', 'BLDR', 'BANF', 'TRIB', 'SVA', 'PFBC', 'IBOC', 'GSBC',
                        'STBA', 'SBSI', 'PLAY', 'OSBC', 'LBRDA', 'KYTH', 'ISBC', 'FNLC', 'BSET', 'BOOM', 'BCOV', 'BANR',
                        'TCBK', 'SHBI', 'MBWM', 'INDB', 'GBCI', 'FBIZ', 'EPAY', 'TCBIP', 'TBBK', 'RCKY', 'MCBC', 'DCOM',
                        'BUFF', 'BANX', 'UBSI', 'TBK', 'RBCAA', 'MRLN', 'FFIN', 'COLB', 'BRLI', 'PWOD', 'PMBC', 'PACW',
                        'ESSA', 'BPMC', 'UBFO', 'RVSB', 'PEBO', 'HWBK', 'HBCP', 'FCBC', 'EBTC', 'BPOPN', 'BFIN', 'BECN',
                        'WTBA', 'TCBIL', 'SYBT', 'BGNE', 'BELFA', 'SIBC', 'LBRDK', 'HBNC', 'FITBI', 'FBNC', 'BPOPM',
                        'SBBP', 'EQBK', 'CTBI', 'BANFP', 'HBANP', 'HBANO', 'MSFT', 'INTC', 'CSCO', 'CMCSA', 'SBUX',
                        'COST', 'CATM', 'NVDA', 'SCTY', 'DISH', 'CERN', 'STX', 'CSX', 'CTSH', 'LRCX', 'SHLD', 'FAST',
                        'WDC', 'GT', 'KLAC', 'CALM', 'CTXS', 'CME', 'CHKP', 'CSIQ', 'GERN', 'CSII', 'SINA', 'FOXA',
                        'KHC', 'WB', 'NWSA', 'CHRW', 'HAIN', 'CLDX', 'CINF', 'CROX', 'CHTR', 'CREE', 'SLM', 'TSCO',
                        'SPTN', 'SPWR', 'CLMT', 'SANM', 'CZR', 'CONN', 'WEN', 'PSEC', 'INCY', 'CTAS', 'GNTX', 'CRUS',
                        'PPC', 'CSGS', 'COLM', 'XONE', 'CYBR', 'ULTA', 'PDCO', 'JAZZ', 'CLVS', 'CBOE', 'OLED', 'CASY',
                        'NUAN', 'MTSC', 'ERIE', 'CLNE', 'UTHR', 'INFN', 'CPLP', 'ZBRA', 'UTSI', 'SIMO', 'SBAC', 'NEOG',
                        'NAVI', 'LKQ', 'LANC', 'CDW', 'SCVL', 'PCH', 'NTRS', 'MASI', 'ISLE', 'CSGP', 'CG', 'CAKE',
                        'SCHL', 'PRTA', 'PRGS', 'NWS', 'MIK', 'LSCC', 'IRBT', 'FOX', 'DISCA', 'CAMP', 'SBRA', 'OTEX',
                        'NCLH', 'HFWA', 'FLDM', 'EMMS', 'COHU', 'UMPQ', 'NDSN', 'GEOS', 'ECPG', 'CAC', 'VICR', 'SATS',
                        'POOL', 'MEOH', 'LOPE', 'LINC', 'FSTR', 'DMRC', 'CDK', 'CASH', 'VOXX', 'PNNT', 'ON', 'MANT',
                        'LMNX', 'HRZN', 'HMSY', 'DISCK', 'CTRN', 'CRTO', 'COWN', 'COMM', 'CCNE', 'TRMK', 'SMCI', 'ROIC',
                        'PRIM', 'PODD', 'NATI', 'HWCC', 'CYTK', 'CWCO', 'CVGW', 'CTRE', 'CSOD', 'CORE', 'CMCO', 'CFMS',
                        'CDNS', 'PLCE', 'PCTY', 'NDLS', 'IPGP', 'HOFT', 'HAFC', 'EFSC', 'CVLT', 'CVBF', 'CNSL', 'CCRN',
                        'CASS', 'UCTT', 'TRS', 'THFF', 'TFSL', 'STRL', 'NWPX', 'MATW', 'IRDM', 'IMMR', 'GLRE', 'FELE',
                        'FDUS', 'CPRT', 'CMTL', 'CCXI', 'CCOI', 'WDFC', 'TW', 'SP', 'SHEN', 'SGMS', 'RNST', 'OTTR',
                        'MTRX', 'IMOS', 'ICLR', 'HMHC', 'GOOD', 'FULT', 'FRME', 'CVGI', 'CSTE', 'CNMD', 'CHEF', 'CHDN',
                        'CHCO', 'CGNX', 'VSEC', 'UMBF', 'QUMU', 'QDEL', 'NCMI', 'HTHT', 'CWST', 'CRAI', 'CHMA', 'CGO',
                        'TCPC', 'SRCE', 'SABR', 'PMTS', 'PLXS', 'PLPC', 'PGC', 'OCFC', 'LNDC', 'LKFN', 'KOPN', 'IART',
                        'CRNT', 'COHR', 'CMPR', 'CFFN', 'ZIXI', 'YORW', 'SMTC', 'SLRC', 'RGEN', 'MIDD', 'HURC', 'GAIN',
                        'CRWN', 'CPSI', 'CHMG', 'WSFS', 'WIRE', 'SPSC', 'PBPB', 'MSEX', 'MCRI', 'LORL', 'GLAD', 'FSRV',
                        'CUTR', 'CONE', 'CHUY', 'CECE', 'CDXS', 'SFNC', 'SEIC', 'PFMT', 'HTBK', 'CTG', 'CRVL', 'CPTA',
                        'COLL', 'CHSCP', 'CEVA', 'CENT', 'CCMP', 'UVSP', 'TAST', 'SUNS', 'SSB', 'PKOH', 'PFIS', 'KRNY',
                        'ITRN', 'GLDD', 'FFIC', 'DWSN', 'CVCO', 'CSWC', 'CPIX', 'CFFI', 'STLY', 'PFLT', 'OXLC', 'OFS',
                        'JRJC', 'JJSF', 'HCCI', 'FUNC', 'FSV', 'FOXF', 'CTHR', 'CSQ', 'CENTA', 'WTFC', 'WLTW', 'TGA',
                        'SENEB', 'SENEA', 'MRCC', 'LMNR', 'ITIC', 'IRCP', 'GTLS', 'DLTR', 'XRAY', 'ODP', 'DXCM', 'ODFL',
                        'DAKT', 'KTOS', 'FANG', 'DMLP', 'STLD', 'DGII', 'DGICA', 'DORM', 'DXPE', 'KRNT', 'DIOD', 'DRNA',
                        'TWIN', 'DSPG', 'DSGX', 'DXLG', 'DLTH', 'QQQX', 'DHIL', 'DISCB', 'DBVT', 'DGICB', 'CHW', 'EBAY',
                        'EXPE', 'EXPD', 'EXEL', 'ENDP', 'EQIX', 'EGHT', 'UEIC', 'MGEE', 'IEP', 'ERIC', 'ECHO', 'STRA',
                        'ERII', 'ENSG', 'EBIX', 'LOCO', 'EXTR', 'EXPO', 'ESGR', 'REGI', 'ECOL', 'PTEN', 'PETS', 'ENTA',
                        'LECO', 'EZPW', 'EXLS', 'ESLT', 'EGOV', 'PDCE', 'EXFO', 'WERN', 'EMITF', 'EEFT', 'SPKE', 'PLUS',
                        'NSIT', 'EHTH', 'VNOM', 'MGIC', 'ETSY', 'ENTG', 'SYKE', 'RELL', 'HEES', 'EPZM', 'ENVI', 'RUSHA',
                        'EDIT', 'HTLD', 'SPI', 'RUSHB', 'KE', 'EBAYL', 'FB', 'FSLR', 'FFIV', 'FISV', 'FLEX', 'FEYE',
                        'FTNT', 'FLIR', 'FLWS', 'PBCT', 'FOSL', 'UFCS', 'SIVB', 'SFM', 'UFPI', 'UNFI', 'FARO', 'SVVC',
                        'LPLA', 'GIFI', 'FRGI', 'FISI', 'FORM', 'FFNW', 'WSBF', 'SAFM', 'GSM', 'FORR', 'VIRT', 'NATH',
                        'FPRX', 'NICK', 'MOFG', 'WAFD', 'PROV', 'HTLF', 'FTEK', 'FORTY', 'FRPH', 'FGEN', 'PNFP', 'FLXS',
                        'FUND', 'WHF', 'WTFCM', 'GILD', 'MRVL', 'VOD', 'GRPN', 'GPRO', 'GRMN', 'TROW', 'Z', 'KNDI',
                        'RGLD', 'GPRE', 'GOLD', 'JCOM', 'HCSG', 'GLUU', 'MYGN', 'LBTYA', 'GOGO', 'HSON', 'SGEN', 'GLNG',
                        'GILT', 'THRM', 'PENN', 'SIGI', 'RUTH', 'LBTYK', 'VNET', 'PRAA', 'GMLP', 'ROCK', 'LILA', 'HUBG',
                        'GSIT', 'GSIG', 'NWLI', 'HCKT', 'GRFS', 'NAME', 'MYRG', 'MTCH', 'LHCG', 'GBLI', 'WEYS', 'GOGL',
                        'IGLD', 'GURE', 'GASS', 'CIGI', 'TRNX', 'SAFT', 'LILAK', 'GOODN', 'GLPG', 'HURN', 'ZG', 'LBTYB',
                        'JRVR', 'GAINN', 'OPK', 'SIRI', 'HAS', 'PYPL', 'MHLD', 'HSIC', 'HA', 'HZNP', 'HIMX', 'HOLX',
                        'HWKN', 'SSNC', 'RYAAY', 'HSII', 'MLHR', 'PICO', 'HSTM', 'HIBB', 'MKTX', 'JBHT', 'SLGN', 'INOV',
                        'HLIT', 'MTSI', 'LGIH', 'HMST', 'HELE', 'MGLN', 'HALO', 'TTEC', 'SPOK', 'HAYN', 'SPWH', 'LITE',
                        'HQY', 'TSC', 'PRAH', 'LTRPA', 'HCM', 'LTRPB', 'SPNE', 'PATI', 'TSLA', 'NFLX', 'QCOM', 'MU',
                        'REGN', 'TXN', 'MAT', 'INO', 'MAR', 'VRTX', 'ZNGA', 'ROST', 'MDLZ', 'TMUS', 'SWKS', 'ISRG',
                        'SRCL', 'PAYX', 'MCHP', 'XLNX', 'MXIM', 'URBN', 'NTAP', 'INTU', 'ILMN', 'PCAR', 'SRPT', 'ICPT',
                        'SOHU', 'NTES', 'YY', 'VRSN', 'SWIR', 'JD', 'NDAQ', 'NVAX', 'TRIP', 'WPRT', 'RMBS', 'RCII',
                        'NYMT', 'PTCT', 'SYNA', 'IDXX', 'PCRX', 'SNPS', 'SPPI', 'PZZA', 'STMP', 'RARE', 'IDCC', 'SPLK',
                        'QRVO', 'ZUMZ', 'YRCW', 'WWD', 'VRNT', 'MMSI', 'INFI', 'IMGN', 'TTWO', 'TTEK', 'MELI', 'LSTR',
                        'SKYW', 'SIEN', 'RAVN', 'NTGR', 'LLNW', 'SNCR', 'MGPI', 'MCRB', 'JAKK', 'ITRI', 'IIIN', 'ZEUS',
                        'TXRH', 'TILE', 'PLAB', 'ORBC', 'NTCT', 'MSTR', 'MPWR', 'JOBS', 'WSBC', 'TREE', 'PTC', 'PRFT',
                        'OMCL', 'OIIM', 'NUVA', 'LYTS', 'LXRX', 'LPSN', 'IRWD', 'WOOF', 'TZOO', 'SEAC', 'SCHN', 'RP',
                        'OSIS', 'MTEX', 'JOUT', 'XBIT', 'WING', 'SEDG', 'QNST', 'PSMT', 'MIND', 'MGI', 'KELYA', 'INSM',
                        'VRTS', 'SAIA', 'QLYS', 'MRCY', 'MORN', 'MERC', 'KVHI', 'IONS', 'IMKTA', 'ICFI', 'VSAT', 'STRS',
                        'SREV', 'SRDX', 'MLAB', 'IIVI', 'UEPS', 'TRUE', 'TEDU', 'STKL', 'RIGL', 'POWL', 'PDFS', 'KPTI',
                        'ITCI', 'ICUI', 'VIAV', 'JSM', 'KMDA', 'KIRK', 'KBAL', 'KFRC', 'KURA', 'KELYB', 'WYNN', 'VIP',
                        'SSYS', 'RDWR', 'WIX', 'NCTY', 'TSEM', 'SHOO', 'MMLP', 'PERI', 'NICE', 'TRMB', 'SILC', 'NVCR',
                        'MRTN', 'LOGI', 'LAWS', 'SLAB', 'LFUS', 'MMYT', 'XNET', 'LQDT', 'PTNR', 'OXLCO', 'CCLP', 'USLM',
                        'NVMI', 'MIME', 'MESO', 'LIVN', 'OXLCP', 'TITN', 'UTMD', 'VISN', 'MOMO', 'MGRC', 'MGNX', 'MDCA',
                        'MARPS', 'MTLS', 'MKSI', 'MCHX', 'VLGEA', 'NYMTO', 'INFO', 'NYMTP', 'NXPI', 'QGEN', 'NKTR',
                        'YNDX', 'QURE', 'OFIX', 'NSSC', 'NNBR', 'NTRA', 'OSUR', 'OTIC', 'QIWI', 'POWI', 'PEGA', 'IPAR',
                        'PATK', 'SNDX', 'PINC', 'PCTI', 'SGRY', 'QADA', 'QADB', 'RUN', 'RNWK', 'RNET', 'RGNX', 'SCSC',
                        'ISSC', 'VRNS', 'SLMBP', 'TWOU', 'TLGT', 'VYGR', 'USAK', 'TRVN', 'TTMI', 'TESS', 'CTMX', 'INVA',
                        'VECO', 'WETF', 'CHSCM', 'CHSCN', 'CHSCL', 'CHSCO', 'CSWI', 'DRIV', 'MFIN', 'COWNL', 'IAC',
                        'IOSP', 'IVAC', 'IVAN', 'RNA', 'VIEW', 'INGN']
